Feature/animated toolbox
praxoc/developer-exercise pull request #1
Opened 2021-03-26 08:05 UTC by praxoc

## Description

### **Create an Animated Toolbox - Advanced (staggered animation)**

**Purpose**

Use CSS to transform a UI pattern without changing the markup.

Create different toolbox versions  using  CSS, CSS transitions, and CSS animations

### **Link to Exercise  (In Basecamp)**

https://3.basecamp.com/4139771/buckets/10262158/documents/2489749402

### **Instructions for  CSS Compiling**

> Open VSCode Editor and Press ctrl+P, type ext install live-sass.

> Install live sass compiler by Ritwick Day

> Click the ‘watch sass’ button on the bottom right of your VSCode screen.

> Click this "Watch Sass" to ensure Live SASS compiler checks for changes in your SASS files and updates your CSS.

### **Instruction to reposition the pill toolbox to left and convert it to circles toolbox**

> Open the css > scss > production.scss file

**To position pill toolbox to left**
> Select line 15 and hit "cmd  + /" in mac OR, "windows + /" in windows

_Note:  This will remove the commented css which will import the file module-toolbox-pill-left and override the pill toolbox positioned right to left_

**To transform pill toolbox to  circle toolbox and position to right**
>  Please comment out line 15 and remove the comment from line 18 which will import the file module-toolbox-circle and override the floating toolbox pills to circles

**To transform pill toolbox to  circle toolbox and position to left**
>  Select line 21 and hit "cmd  + /" in mac OR, "windows + /" in windows

_Note: This scss file is a combination of all 3 modules which will automatically convert the pills to circle and postion toolbox to left._

## Checklist

Make sure the following tasks have been completed before you submit this pull request:

- [ ] Used mixins and variables to avoid unnecessary code duplication .
- [x] SCSS partial names should have `_underscores`.
- [x] Indentation follows style guide (2 spaces soft tabs HTML and CSS).
- [x] Only classes styled (not element selectors).
- [x] All elements have classes.
- [x] Class names are meaningful and consistent.
- [x] Class names follow style guidelines.
- [x] Style rules follow markup order.
- [x] Checked there is no unnecessary nesting of SCSS rules.
- [x] Deleted unused css properties.
- [x] No duplicate class names in SCSS partials.
- [x] No duplicate properties within a rule.
- [x] Validated markup wih w3C Validator.
- [x] Tested and fixed fonts.
- [x] Included all font formats.
- [x] Added `.gitignore` file.
- [x] Fixed browser console errors.
- [x] Compared front-end with mock up side by side.
- [x] Tested local production `production.css`.
- [x] Tested on mobile, preferably iOS Safari or equivalent Android.
- [x] Tested in Chrome.
- [x] Tested in Firefox.
- [x] Tested in Edge, if available.
- [x] Merged `develop` into your feature branch, multiple times as needed.

You can strike-through items that are not ~~relevant~~.

2021-03-27 02:54 UTC, pixelsoup requested changes
- You should only have one .gitignore - in the root
- Move the files ignored from animated_toolbox/.gitignore to the .gitignore in root 
- Delete animated_toolbox/.gitignore 
- Delete basic_toolbox/.gitignore
- Delete the other repository [imotor-exercises](https://github.com/praxoc/imotor-exercises). It's not being updated.

2021-03-27 09:48 UTC, merged

2021-03-29 22:31 UTC, pixelsoup commented on animated_toolbox/css/scss/_external-fonts.scss
> +  src: url("../fonts/Roboto-Regular.ttf") format("truetype"), url("../fonts/Roboto-Regular.woff") format("woff"), url("../fonts/Roboto-Regular.woff2") format("woff2");
@praxoc the fonts are listed in the wrong order. Browsers download the first font it's compatible with. If it's not compatible with one it will go to the next. In this case Chrome will download the .ttf file ([caniuse](https://caniuse.com/ttf)). For the best user experience you want the browser to download the smallest font files and .ttf files are usually the largest

2021-03-29 22:31 UTC, pixelsoup commented on animated_toolbox/css/scss/_external-fonts.scss
> +  font-weight: 400;
@praxoc
1. Do you need font-weight here? 
2. What does it do?

2021-03-29 22:31 UTC, pixelsoup commented on animated_toolbox/css/scss/_external-fonts.scss
> +  font-weight: 300;
see comment above about font-weight.

2021-03-29 22:31 UTC, pixelsoup commented on animated_toolbox/css/scss/_layout.scss
> +}
@praxoc This isn't the recipe I linked to in my previous feedback. Please read [Paul Irish's 2012 FTW post](https://www.paulirish.com/2012/box-sizing-border-box-ftw/) and use his code. This guy knows what he's talking about (front-end developer, works on the Google Chrome team.)
```suggestion

/* apply a natural box layout model to all elements, but allowing components to change */
html {
  box-sizing: border-box;
}
*, *:before, *:after {
  box-sizing: inherit;
}

```

2021-03-29 22:31 UTC, pixelsoup commented on animated_toolbox/css/scss/_mixin-fonts.scss
> +  font-weight: 400;
@praxoc 
1. Double property (not changed from previous feedback)
2. Do you need **ANY** font-weight here? 
3. What does font-weight do?

2021-03-29 22:31 UTC, pixelsoup commented on animated_toolbox/css/scss/_mixin-fonts.scss
> +  font-weight: 300;
@praxoc 
1. Double property (same as before)
2. Do you need **ANY** font-weight here? 
3. What does font-weight do?

2021-03-29 22:31 UTC, pixelsoup commented on animated_toolbox/css/scss/_mixin-fonts.scss
> +  font-family: "Roboto Regular", Helvetica, Arial, sans-serif;
@praxoc These font names won't work (no change from previous feedback)

2021-03-29 22:31 UTC, pixelsoup commented on animated_toolbox/css/scss/_mixin-fonts.scss
> +  font-family: "Roboto Light", Helvetica, Arial, sans-serif;
@praxoc These font names won't work (no change from previous feedback)

2021-03-29 22:31 UTC, pixelsoup commented on animated_toolbox/css/scss/_module-toolbox-pill.scss
> +  }
- Please refactor to avoid unnecessary code duplication
- Easier to maintain

```suggestion
  &:nth-child(1) {

    .toolbox-heading-wrapper,
    .toolbox-icon-svg {
      animation-delay: 100ms;
    }
  }
  
  etc...
```

2021-03-29 22:31 UTC, pixelsoup commented on animated_toolbox/.gitignore
> +.DS_Store
- Delete this file
- See comment about .gitignore in root only

2021-03-29 22:31 UTC, pixelsoup commented on animated_toolbox/css/fonts/LICENSE.txt
> +
- Delete this file 
- It has no purpose

2021-03-29 22:56 UTC, praxoc commented on animated_toolbox/css/scss/_external-fonts.scss
> +  src: url("../fonts/Roboto-Regular.ttf") format("truetype"), url("../fonts/Roboto-Regular.woff") format("woff"), url("../fonts/Roboto-Regular.woff2") format("woff2");
- Thanks for awareness @pixelsoup , I will change the order now.

2021-03-29 22:57 UTC, praxoc commented on animated_toolbox/css/scss/_external-fonts.scss
> +  font-weight: 400;
It's presetting robot-regular to 400.

2021-03-29 22:57 UTC, praxoc commented on animated_toolbox/css/scss/_external-fonts.scss
> +  font-weight: 300;
It's presetting robot-light to 300.

2021-03-29 23:01 UTC, praxoc commented on animated_toolbox/css/scss/_layout.scss
> +}
Awesome. Will modify the code now. Thanks !

2021-03-29 23:01 UTC, praxoc commented on animated_toolbox/css/scss/_mixin-fonts.scss
> +  font-weight: 400;
Not really. Sorry I missed this one.